<?php

/**
 * Implements hook_menu().
 */
function mybrary_web_inventory_menu() {
  $items = array();

  $items['inventory'] = array(
            'title' => t('Inventory'),
            'page callback' => 'mybrary_web_inventory',
            'file' => 'mybrary_web_inventory.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
  );
  
  $items['inventory/main'] = array(
            'title' => t('Inventory'),
            'page callback' => 'mybrary_web_inventory_main',
            'file' => 'mybrary_web_inventory.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
  );
  
  return $items;
}