<?php

/**
 * Implements hook_menu().
 */
function mybrary_web_menu ()
{
    $items['welcome'] = array(
            'title' => t('Welcome'),
            'page callback' => 'mybrary_web_welcome_page',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => TRUE
    );
    
    $items['app'] = array(
            'title' => t('App'),
            'page callback' => 'mybrary_web_app',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
    );

    $items['tpl/dashboard'] = array(
            'title' => t('Dashboard'),
            'page callback' => 'mybrary_web_dashboard',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
    );
    
    $items['tpl/connection-list'] = array(
            'title' => t('Connection'),
            'page callback' => 'mybrary_web_connection_list',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
    );
    
    $items['tpl/connection-view'] = array(
            'title' => t('Connection'),
            'page callback' => 'mybrary_web_connection_view',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
    );
    
    $items['tpl/inventory-list'] = array(
            'title' => t('Inventory'),
            'page callback' => 'mybrary_web_inventory_list',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
    );
    
    $items['tpl/inventory-edit'] = array(
            'title' => t('Inventory'),
            'page callback' => 'mybrary_web_inventory_edit',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
    );
    
    $items['tpl/search'] = array(
            'title' => t('Search'),
            'page callback' => 'mybrary_web_search',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
    );
    
    $items['tpl/transaction'] = array(
            'title' => t('Transaction'),
            'page callback' => 'mybrary_web_transaction',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
    );
    
    $items['tpl/transaction-list'] = array(
            'title' => t('Transaction'),
            'page callback' => 'mybrary_web_transaction_list',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
    );
    
    $items['tpl/notification-list'] = array(
            'title' => t('Transaction'),
            'page callback' => 'mybrary_web_notification_list',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_NORMAL_ITEM,
            'access callback' => 'user_is_logged_in'
    );
    
    $items['ajax/image-upload'] = array(
            'page callback' => 'mybrary_web_ajax_image_upload',
            'delivery callback' => 'mybrary_web_ajax_delivery_callback',
            'file' => 'mybrary_web.page.inc',
            'type' => MENU_CALLBACK,
            'access callback' => 'user_is_logged_in'
    );
    
    return $items;
}