<?php
/**
 * User type constant
 */
define("MYBRARY_USER_TYPE_UNKNOWN", 0);
define("MYBRARY_USER_TYPE_DRUPAL", 1);
define("MYBRARY_USER_TYPE_FACEBOOK", 2);

/**
 * User relationship status constant
 */
define("MYBRARY_USER_RELATIONSHIP_STATUS_UNKNOWN", 0);
define("MYBRARY_USER_RELATIONSHIP_STATUS_CONFIRMED", 1);
define("MYBRARY_USER_RELATIONSHIP_STATUS_REJECTED", 2);
define("MYBRARY_USER_RELATIONSHIP_STATUS_REQUESTED", 3);

function _mybrary_user_get_status_label ($key) {
    $labels = array(
            MYBRARY_USER_RELATIONSHIP_STATUS_UNKNOWN => t('unknown'),
            MYBRARY_USER_RELATIONSHIP_STATUS_CONFIRMED => t('confirmed'),
            MYBRARY_USER_RELATIONSHIP_STATUS_REJECTED => t('declined'),
            MYBRARY_USER_RELATIONSHIP_STATUS_REQUESTED => t('requested'),
    );

    if (array_key_exists($key, $labels)) {
        return $labels[$key];
    } else {
        return t('Unknown status label for key: !key', array('!key' => $key));
    }
}

/**
 * Hook to manually save Facebook data after a user has connected.
 *
 * This hook is fired after a Drupal user account is created by the Facebook
 * OAuth module.
 *
 * @param $account
 *   A full Drupal user account object.
 * @param $fbuser
 *   The Facebook user account. Note that the contents of this object may change
 *   depending on what access the user has granted.
 * @return
 *   None.
 *
 * @see hook_fboauth_user_presave()
 */
function mybrary_user_fboauth_user_save($account, $fbuser) {
    
    // Save the Facebook user info into a custom table.
    $mydate = array(
            'uid' => $account->uid,
            'type' => MYBRARY_USER_TYPE_FACEBOOK,
            'ext_id' => $fbuser->id,
            'ext_name' => $fbuser->name,
            'data' => NULL,
            'update_timestamp' => time(),
    );
    drupal_write_record('mybrary_user_ext', $mydate);
}

/**
 * Alter the list of Facebook Actions provided through hook_fboauth_actions().
 *
 * @see fboauth_fboauth_actions().
 */
function mybrary_user_fboauth_actions_alter(&$actions) {
    // Replace the normal login callback with custom login callback.
    $actions['connect']['callback'] = 'mybrary_user_fboauth_action_connect';
    
    // force to add the required permissions
    $permissions = array(
            'email',
            'user_friends',
            'publish_actions'
    );
    $actions['connect']['permissions'] = $actions['connect']['permissions'] + $permissions;
}


/**
 * Customized Facebook OAuth callback for initiating a Facebook connection.
 */
function mybrary_user_fboauth_action_connect($app_id, $access_token) {
    global $user;
    
    // logout the current drupal user if it has not been associated with a facebook account.
    module_load_include('inc', 'fboauth', 'includes/fboauth.fboauth');
    if ($user->uid) {
        $fbid = fboauth_fbid_load($user->uid);
        if (!$fbid) {
            watchdog('user', 'Session closed for %name to proceed facebook login.', array('%name' => $user->name));
            module_invoke_all('user_logout', $user);
            // Destroy the current session, and reset $user to the anonymous user.
            session_destroy();
            return;
        }
    }
    
    // call the original function to initialize the connection
    fboauth_action_connect($app_id, $access_token);
    
    $fbuser = fboauth_graph_query('me', $access_token);
    if ($fbuser) {
        $uid = fboauth_uid_load($fbuser->id);
        // fb user connected (redundent check)
        if ($uid && ($account = user_load($uid))) {
            // fb user logged in
            if ($account->uid == $user->uid) {

                // Get all friends to create the user relationship.
                $fbResponse = fboauth_graph_query('me/friends', $access_token);
                if ($fbResponse) {
                    $fbFriendIds = array();
                    foreach($fbResponse->data as $fbFriend) {
                        $fbFriendIds[] = $fbFriend->id;
                    }
                }
                
                // Get users not in relationship to create.
                if (!empty($fbFriendIds)) {
                    $result = db_select('mybrary_user_ext', 'u')->fields('u', array('uid'))
                    ->condition('u.ext_id', $fbFriendIds, 'IN')
                    ->condition('u.type', MYBRARY_USER_TYPE_FACEBOOK)
                    ->execute();
                    
                    // Create the Facebook user relationship.
                    while ($row = $result->fetchAssoc()) {
                        
                        // Detecte existing relationship.
                        if(!(db_query('SELECT 1 FROM {mybrary_user_net} WHERE uid_from = :uid_from AND uid_to = :uid_to', 
                        array(':uid_from'=>$user->uid, ':uid_to'=>$row['uid']))->fetchField())) {
                            $mydate = array(
                                    'uid_from' => $user->uid,
                                    'uid_to' => $row['uid'],
                                    'update_timestamp' => time(),
                            );
                            drupal_write_record('mybrary_user_net', $mydate);
                        }
                        
                        // Detecte existing relationship.
                        if(!(db_query('SELECT 1 FROM {mybrary_user_net} WHERE uid_from = :uid_from AND uid_to = :uid_to', 
                        array(':uid_from'=>$row['uid'], ':uid_to'=>$user->uid))->fetchField())) {
                            $mydate = array(
                                    'uid_from' => $row['uid'],
                                    'uid_to' => $user->uid,
                                    'update_timestamp' => time(),
                            );
                            drupal_write_record('mybrary_user_net', $mydate);
                        }
                    }
                }
                
                //@TODO replace below auto confirm relationship with user interactive
                $result = db_update('mybrary_user_net')
                ->fields(array(
                    'status' => MYBRARY_USER_RELATIONSHIP_STATUS_CONFIRMED
                ))
                ->condition('uid_from', $user->uid)
                ->condition('status', MYBRARY_USER_RELATIONSHIP_STATUS_UNKNOWN)
                ->execute();
                
                $result = db_update('mybrary_user_net')
                ->fields(array(
                    'status' => MYBRARY_USER_RELATIONSHIP_STATUS_CONFIRMED
                ))
                ->condition('uid_to', $user->uid)
                ->condition('status', MYBRARY_USER_RELATIONSHIP_STATUS_UNKNOWN)
                ->execute();
                
                //@TODO remove the not existing anymore relationship
            }
        }
    }
}

/**
 * Implements hook_user_delete().
 */
function mybrary_user_user_delete($account) {
    // Delete any existing extended user info and relationship.
    db_delete('mybrary_user_ext')
    ->condition('uid', $account->uid)
    ->execute();

    db_delete('mybrary_user_net')
    ->condition('uid_from', $account->uid)
    ->execute();
    
    db_delete('mybrary_user_net')
    ->condition('uid_to', $account->uid)
    ->execute();
}

/**
 * Implements hook_user_cancel().
 */
function mybrary_user_user_cancel($edit, $account, $method) {
    mybrary_user_user_delete($account);
}

/**
 * Get friend ids
 * 
 * @param integer $uid
 */
function _mybrary_user_get_friends ($uid, $status = NULL) {
    
    $result = array();
    
    if (!empty($uid)) {
        $query = db_select('mybrary_user_net', 'n');
        $query->addField('n', 'uid_to');
        $query->condition('n.uid_from', $uid);
        
        // default only show confirmed
        if (empty($status)) {
            $status = array(
                MYBRARY_USER_RELATIONSHIP_STATUS_CONFIRMED
            );
        }
        
        $query->condition('n.status', $status);
        $dbResult = $query->execute();

        while ($row = $dbResult->fetchAssoc()) {
            $result[] = $row['uid_to'];
        }
    }
    
    return $result;
}

/**
 * Get friend of friend ids
 *
 * @param integer $uid
 */
function _mybrary_user_get_friends_of_friends ($uid, $friendIncluded = FALSE) {

    $result = array();

    if (!empty($uid)) {
        $friends = _mybrary_user_get_friends($uid);
        $fofriends = _mybrary_user_get_friends($friends);

        if ($friendIncluded) {
            $result = array_merge($fofriends, $friends);
        } else {
            $result = array_diff($fofriends, $friends);
        }
        
        // always exclude self
        $result = array_diff($result, array($uid));
    }

    return $result;
}

function _mybrary_user_list ($uid)
{
    global $user;
    global $base_path;

    $response = array();
    if (!empty($uid)) {
        try {
            $query = db_select('users', 'u');
            $query->join('mybrary_user_ext', 'e', 'e.uid = u.uid');
            $query->leftJoin('file_managed', 'f', 'u.picture = f.fid');
            $query->fields('u', array('uid', 'name'));
            $query->addField('e', 'ext_id', 'externalId');
            $query->addField('e', 'ext_name', 'externalName');
            $query->addField('e', 'type', 'externalType');
            $query->addField('f', 'uri', 'pictureUri');
            $query->condition('u.uid', $uid);
    
            $dbResult = $query->execute();
    
            $response = array();
            while ($row = $dbResult->fetchAssoc()) {
                $row['pictureUrl'] = ($row['pictureUri'] ? file_create_url($row['pictureUri'])
                        : $base_path . drupal_get_path('theme', 'mybrary') . '/images/unknown-user.png');
                $response[$row['uid']] = $row;
            }
        } catch (Exception $e) {
            watchdog('_mybrary_user_list',
                    'User list error  [' . $e->getCode() . '] ' .
                    $e->getMessage(), NULL, WATCHDOG_ERROR);
            throw $e;
        }
    }

    return $response;
}
