<?php
/**
 * Implements hook_field_attach_submit ($entity_type, $entity, $form, &$form_state, $options = array())
 */
function mybrary_user_field_attach_submit ($entity_type, $entity, $form,
        &$form_state, $options = array())
{
    // Copy top-level form values that are for fields to entity properties
    if ($entity_type == 'user') {

        $fields_values = array_intersect_key($form_state['input'],
                field_info_instances($entity_type, 'user'));

        foreach ($fields_values as $key => $value)
        {
            switch ($key)
            {
                default:
                    $entity->$key = $value;
            }
        }
    }
}