<?php
/**
 * Transaction status constant
 */
define("MYBRARY_TRANSACTION_STATUS_UNKNOWN", 0);
define("MYBRARY_TRANSACTION_STATUS_REQUESTED", 1);
define("MYBRARY_TRANSACTION_STATUS_CONFIRMED", 2);
define("MYBRARY_TRANSACTION_STATUS_DECLINED", 3);
define("MYBRARY_TRANSACTION_STATUS_RECEIVED", 4);
define("MYBRARY_TRANSACTION_STATUS_RETURNED", 5);

function _mybrary_transaction_get_status_label ($key) {
    $labels = array(
            MYBRARY_TRANSACTION_STATUS_UNKNOWN => t('unknown'),
            MYBRARY_TRANSACTION_STATUS_REQUESTED => t('requested'),
            MYBRARY_TRANSACTION_STATUS_CONFIRMED => t('confirmed'),
            MYBRARY_TRANSACTION_STATUS_DECLINED => t(' declined'),
            MYBRARY_TRANSACTION_STATUS_RECEIVED => t(' received'),
            MYBRARY_TRANSACTION_STATUS_RETURNED => t(' returned'),
    );
    
    if (array_key_exists($key, $labels)) {
        return $labels[$key];
    } else {
        return t('Unknown label for key: !key', array('!key' => $key));
    }
}
