<?php
/**
 * @file
 * Code for the Mybrary Service feature.
 */

include_once 'mybrary_service.features.inc';

/**
 * Implements hook_services_resources().
 */
function mybrary_service_services_resources ()
{
    return array(
            'term' => array(
                    'actions' => array(
                            'list' => array(
                                    'help' => t('List all term'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.term.api'
                                    ),
                                    'callback' => 'mybrary_service_term_list',
                                    'access callback' => 'mybrary_service_term_resource_access',
                                    'access arguments' => array('list'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            )
                    )
            ),
            'inventory' => array(
                    'actions' => array(
                            'list' => array(
                                    'help' => t('List inventory'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.inventory.api'
                                    ),
                                    'callback' => 'mybrary_service_inventory_list',
                                    'access callback' => 'mybrary_service_inventory_resource_access',
                                    'access arguments' => array('list'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),
                            'view' => array(
                                    'help' => t('View inventory'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.inventory.api'
                                    ),
                                    'callback' => 'mybrary_service_inventory_view',
                                    'access callback' => 'mybrary_service_inventory_resource_access',
                                    'access arguments' => array('view'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),
                            'update' => array(
                                    'help' => t('Update inventory'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.inventory.api'
                                    ),
                                    'callback' => 'mybrary_service_inventory_update',
                                    'access callback' => 'mybrary_service_inventory_resource_access',
                                    'access arguments' => array('update'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),
                            'delete' => array(
                                    'help' => t('Delete inventory'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.inventory.api'
                                    ),
                                    'callback' => 'mybrary_service_inventory_delete',
                                    'access callback' => 'mybrary_service_inventory_resource_access',
                                    'access arguments' => array('view'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            )
                    )
            ),
            'transaction' => array(
                    'actions' => array(
                            'list' => array(
                                    'help' => t('List transaction'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.transaction.api'
                                    ),
                                    'callback' => 'mybrary_service_transaction_list',
                                    'access callback' => 'mybrary_service_transaction_resource_access',
                                    'access arguments' => array('list'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),
                            'view' => array(
                                    'help' => t('View transaction'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.transaction.api'
                                    ),
                                    'callback' => 'mybrary_service_transaction_view',
                                    'access callback' => 'mybrary_service_transaction_resource_access',
                                    'access arguments' => array('view'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),
                            'update' => array(
                                    'help' => t('Update transaction'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.transaction.api'
                                    ),
                                    'callback' => 'mybrary_service_transaction_update',
                                    'access callback' => 'mybrary_service_transaction_resource_access',
                                    'access arguments' => array('update'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),
                            'remind-return' => array(
                                    'help' => t('Remind return'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.transaction.api'
                                    ),
                                    'callback' => 'mybrary_service_transaction_remind_return',
                                    'access callback' => 'mybrary_service_transaction_resource_access',
                                    'access arguments' => array('remind-return'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),
                            'delete' => array(
                                    'help' => t('Delete transaction'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.transaction.api'
                                    ),
                                    'callback' => 'mybrary_service_transaction_delete',
                                    'access callback' => 'mybrary_service_transaction_resource_access',
                                    'access arguments' => array('view'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            )
                    )
            ),
            'connection' => array(
                    'actions' => array(
                            'invite' => array(
                                    'help' => t('Invite friend'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.connection.api'
                                    ),
                                    'callback' => 'mybrary_service_connection_invite',
                                    'access callback' => 'mybrary_service_connection_resource_access',
                                    'access arguments' => array('invite'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),
                            'request-to-add' => array(
                                    'help' => t('Request to add friend'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.connection.api'
                                    ),
                                    'callback' => 'mybrary_service_connection_request_to_add',
                                    'access callback' => 'mybrary_service_connection_resource_access',
                                    'access arguments' => array('request-to-add'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),                            
                            'response-to-add' => array(
                                    'help' => t('Response to add friend'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.connection.api'
                                    ),
                                    'callback' => 'mybrary_service_connection_response_to_add',
                                    'access callback' => 'mybrary_service_connection_resource_access',
                                    'access arguments' => array('response-to-add'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),                            
                            'list' => array(
                                    'help' => t('List connection'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.connection.api'
                                    ),
                                    'callback' => 'mybrary_service_connection_list',
                                    'access callback' => 'mybrary_service_connection_resource_access',
                                    'access arguments' => array('list'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),
                            'view' => array(
                                    'help' => t('View friend'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.connection.api'
                                    ),
                                    'callback' => 'mybrary_service_connection_view',
                                    'access callback' => 'mybrary_service_connection_resource_access',
                                    'access arguments' => array('view'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            )
                    )
            ),
            'notification' => array(
                    'actions' => array(
                            'list' => array(
                                    'help' => t('List notification'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.notification.api'
                                    ),
                                    'callback' => 'mybrary_service_notification_list',
                                    'access callback' => 'mybrary_service_notification_resource_access',
                                    'access arguments' => array('list'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            ),
                            'update' => array(
                                    'help' => t('Update notification'),
                                    'file' => array(
                                            'type' => 'inc',
                                            'module' => 'mybrary_service',
                                            'name' => 'mybrary_service.notification.api'
                                    ),
                                    'callback' => 'mybrary_service_notification_update',
                                    'access callback' => 'mybrary_service_notification_resource_access',
                                    'access arguments' => array('update'),
                                    'access arguments append' => TRUE,
                                    'args' => array(
                                            array(
                                                    'name' => 'data',
                                                    'type' => 'array',
                                                    'description' => t('Parameters of the action'),
                                                    'source' => 'data',
                                                    'optional' => FALSE
                                            )
                                    )
                            )
                    )
            )
    );
}
   
/**
 * Get rid of wrapper for field value
 * _mybrary_service_get_field_value ($entity, $fik, $fio).
 * 
 * @param Entity $entity
 * @param string $fik, field name
 * @param array $fio, field value processing options
 * @return single value or array
 */
function _mybrary_service_get_entity_field_value ($entity, $fik, $fio)
{
   $values = NULL;
    
   if ($fio && $fio['is_property'] && isset($entity->{$fik})) {
       $values = $entity->{$fik};
       
   } elseif (!empty($entity->{$fik}) && !empty($entity->{$fik}[$entity->language])) {
        $values = array();
        
        // process each item in the field
        foreach($entity->{$fik}[$entity->language] as $v)
        {
            $valueConvertorName = "default";
            if ($fio && isset($fio['value_convertor']) 
            && function_exists("_mybrary_service_entity_field_value_convertor_{$fio['value_convertor']}")) {
                $valueConvertorName = $fio['value_convertor'];
            }
            
            $values[] = call_user_func("_mybrary_service_entity_field_value_convertor_{$valueConvertorName}", $v, $entity, $fik, $fio);
        }
    }
    
    // process the whole field
    $valuesConvertorName = "default";
    if ($fio && isset($fio['values_convertor'])
    && function_exists("_mybrary_service_entity_field_values_convertor_{$fio['values_convertor']}")) {
        $valuesConvertorName = $fio['values_convertor'];
    }

    $values= call_user_func("_mybrary_service_entity_field_values_convertor_{$valuesConvertorName}", $values, $entity, $fik, $fio);
    
    return $values;
}

/********************************************************************
 * entity field convertors
 *******************************************************************/

function _mybrary_service_entity_field_value_convertor_default ($v, $entity, $fik, $fio) {
    return (isset($v['value']) ? $v['value'] : (isset($v['tid']) ? $v['tid'] : (isset($v['nid']) ? $v['nid'] : (isset($v['uid']) ? $v['uid'] : $v))));
}

function _mybrary_service_entity_field_value_convertor_image ($v, $entity, $fik, $fio) {
    $a=1;
    return array(
        'filename'=> $v['filename'],
        'url'=> file_create_url($v['uri']),
    );
}

/********************************************************************
 * entity field values convertors
 *******************************************************************/

function _mybrary_service_entity_field_values_convertor_default ($values, $entity, $fik, $fio) {
    // do nothing
    return $values;     
}

function _mybrary_service_entity_field_values_convertor_single_value ($values, $entity, $fik, $fio) {
    if (!empty($values)) {
        $values = $values[0];
    } else {
        $values = NULL;
    }
    return $values;
}